/*
CREATED BY SAMIRA ALVES LUCIO DIAS
DATE: 20/08/2020
GOAL: Report developed to return exams realized on predetermined sectors
*/

CREATE OR REPLACE FORCE VIEW VDIC_ELETROCARDIOGRAMA (
       CD_PED_RX
      ,CD_LAUDO
      ,CD_EXA_RX
      ,DS_EXA_RX
      ,CD_PRESTADOR
      ,NM_PRESTADOR
      ,DT_REALIZADO
      ,CD_ATENDIMENTO
      ,NM_PACIENTE
) AS
SELECT ITPED_RX.CD_PED_RX
      ,ITPED_RX.CD_LAUDO
      ,ITPED_RX.CD_EXA_RX
      ,EXA_RX.DS_EXA_RX
      ,ITPED_RX.CD_PRESTADOR
      ,PRESTADOR.NM_PRESTADOR
      ,to_char(ITPED_RX.DT_REALIZADO,'DD/MM/YYYY')DT_REALIZADO
      ,PED_RX.CD_ATENDIMENTO
      ,PACIENTE.NM_PACIENTE
 FROM ITPED_RX ITPED_RX
INNER JOIN EXA_RX EXA_RX
  ON ITPED_RX.CD_EXA_RX = EXA_RX.CD_EXA_RX
INNER JOIN PRESTADOR PRESTADOR
  ON PRESTADOR.CD_PRESTADOR = ITPED_RX.CD_PRESTADOR
INNER JOIN PED_RX PED_RX
  ON PED_RX.CD_PED_RX = ITPED_RX.CD_PED_RX
INNER JOIN ATENDIME ATENDIME
  ON ATENDIME.CD_ATENDIMENTO = PED_RX.CD_ATENDIMENTO
INNER JOIN PACIENTE PACIENTE
  ON PACIENTE.CD_PACIENTE = ATENDIME.CD_PACIENTE
WHERE ITPED_RX.CD_EXA_RX IN ('13','16','17','125')
--AND TRUNC (ITPED_RX.DT_REALIZADO) BETWEEN '01/08/2018' AND '31/08/2018'
ORDER BY ITPED_RX.DT_REALIZADO
        ,PACIENTE.NM_PACIENTE
/
GRANT SELECT ON VDIC_ELETROCARDIOGRAMA TO biconexao;
GRANT SELECT ON VDIC_ELETROCARDIOGRAMA TO dbacp WITH GRANT OPTION;
GRANT SELECT ON VDIC_ELETROCARDIOGRAMA TO dbaportal WITH GRANT OPTION;
GRANT DELETE,INSERT,SELECT,UPDATE ON VDIC_ELETROCARDIOGRAMA TO dbaps;
GRANT DELETE,INSERT,SELECT,UPDATE ON VDIC_ELETROCARDIOGRAMA TO dbasgu;
GRANT DELETE,INSERT,SELECT,UPDATE ON VDIC_ELETROCARDIOGRAMA TO mv2000;
GRANT DELETE,INSERT,SELECT,UPDATE ON VDIC_ELETROCARDIOGRAMA TO mvintegra;